- allocated-pids.txt
Hi, I'm working on an MCU called the RoboCloud. It is an ESP32-S2 motor driver board with Adafruit Stemma QT/Sparkfun Qwicc and a bunch of exposed IO pins. It is designed to drive 2 4.5A motors. I'm building CircuitPython and need a PID.
Thanks!
> PID for Project Stida RoboCloud

- allocated-pids.txt
Request for USB PIDS for ESP32-S2 lolin S2-Pico for Arduino, Circuitpython, Uf2 Bootloader.
> Lolin S2-Pico

- allocated-pids.txt
added 3 PIDS for new ESP32S3 custom board
> CircuitArt FeatherS3 development custom board

- allocated-pids.txt
- App controlled music boxes with USB MIDI input
- ESP32-S3
- It will be new products on our new hardware
- Tevofy Technology LTD. 酷鳩科技股份有限公司
- murobox.com
> add Muro Box MIDI PIDs

- allocated-pids-espressif-devboards.txt
Thank you so much for the S2 DevKitC! It's really nice to have both USB broken out.
> PIDs for S2 DevKitC and S3 USB-OTG

- allocated-pids.txt
I am working to bring up the C3 Mini on CircuitPython and we'll need a PID.
PR for that work here: https://github.com/adafruit/circuitpython/pull/6256
> PID Request for Lolin C3 Mini on CircuitPython

- allocated-pids.txt
I'm requesting 1x PIDs for my ESP32-S2 based Reflow Master Pro
I am requesting this PIDs on behalf on my Company, Unexpected Maker
Thanks!
> Added Unexpected Maker - Reflow Master Pro (ESP32-S2)

- allocated-pids.txt
Waveshare makes my brain hurt.
Please refer to:
https://github.com/adafruit/circuitpython/pull/6672
> Add Waveshare ESP32-S2-Pico

- allocated-pids.txt
the bee motion is a esp32-s2 board with a PIR sensor on it that i sell. see here https://www.tindie.com/products/smartbee/bee-motion-esp32-pir-motion-sensor/
the Bee S3 and Bee Motion S3 are similar boards that are soon to be released. both use the ESP32-S3 chip.
requesting on behalf of my company Smart Bee Designs
why i need this - for device identification
> added smart bee designs boards

- allocated-pids.txt
> Add PIDs for Lolin S3 board

- allocated-pids.txt
Added PIDs for RIKA FireNet 2.0 USB-WiFi Stick (Bootloader and Application)
> Added PIDs for RIKA FireNet 2.0 USB-WiFi Stick

- allocated-pids.txt
More info on the board can be found here
* https://github.com/Xinyuan-LilyGO/T-Display-S3
* https://www.lilygo.cc/products/t-display-s3?variant=42284559827125
> Added PIDs for T-Display-S3

- allocated-pids.txt
the "Bee Data Logger" is a soon to be released Esp32-s3 data logger board. requesting on behalf of my company Smart Bee Designs LLC why i need this - for device identification
> Added a Smart Bee Design Board

- allocated-pids.txt
StampS3 [Doc Link](https://docs.m5stack.com/en/core/StampS3)
TimerCamS3 under develop.
> Request M5Stack StampS3 & TimerCamS3 board PIDs

- allocated-pids.txt
New pull request for LAEPI safe.EAR by Rafael Gerges
> Add LAEPI safe.EAR (S3)

- .github/workflows/check-format.yml
- allocated-pids.txt
- check-file-format.sh
So I don't overlook stupid typos that are hard to see (B instead of 8)
> Add CI checks for file sanity

- allocated-pids.txt
Working on a mesh data-logging network to commission large HVAC installs
ESP32-S2
Primarily auto-detecting connected devices for configuration and FW upload
Command Commissioning LLC
[Here](https://command-cx.com/) is the company webpage! Product is still very much in development, so not much info available at this time
> Add CCLLC Sensor mesh

- allocated-pids.txt
**Device Description:** 
The Busy Tag is a versatile communication device designed for personal expression and connectivity. It utilizes a full-color display for customizable visuals and LED patterns, supported by Bluetooth for wireless updates and USB for charging and data transfer.
**Chip Used:** 
The device utilizes the ESP32-S3 Mini, chosen for its powerful features including Wi-Fi and Bluetooth connectivity, ideal for supporting the Busy Tag's multifunctional capabilities.
**Need for Custom PID:** 
A custom PID under our own VID is crucial to ensure our Busy Tag devices are uniquely identified and properly supported across different platforms. This aids in avoiding conflicts with other USB devices and ensures a seamless user experience.
**Company Name:** 
The product is developed by …
> Added PID for BUSY TAG

- allocated-pids.txt
MRC (Model Rectifier Corporation) is developing a new product line based on the ESP32-S3 using the USB interface for a PC interface used for logging and interfacing with JMRI (or similar applications).
Information about some of the upcoming products can be seen [here](https://www.modelrectifier.com/category-s/372.htm). Additional products are planned for the future
> Add MRC Nexxt Product IDs

- allocated-pids.txt
PID request for BlueRetro Xbox adapter.
> Add BlueRetro X BT Adapter

- .github/workflows/check-format.yml
Check to make sure a PR didn't accidentally somehow remove a line. The textfiles should normally only be added to.
> Check for removed lines

- allocated-pids.txt
I got my hands on this board.
Info can be found on it at:
https://www.aliexpress.com/item/1005005642999869.html
and
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/t-watch-s3
I have no affiliation with the board maker.
I just got the board and want to make an official CircuitPython port.
TinyUF2 PR: https://github.com/adafruit/tinyuf2/pull/399
CircuitPython PR: https://github.com/adafruit/circuitpython/pull/9480
> Add LILYGO T-Watch-S3

- allocated-pids.txt
Added Padauk Programmer - Arduino
It is using ESP32-S3
kohacraft.com
> Add kohacraft.com Padauk Programmer

- allocated-pids.txt
CharaChorder Master Forge S3 (M4G) is a chording enabled USB keyboard.
ESP32-S3
The device pairs with serial applications that need PIDs for filtering valid devices
CharaChorder, LLC
The product page is here:
https://forgekeyboard.com/products/master-forge
> added PID request for CharaChorder Master Forge

- allocated-pids.txt
Add LILYGO new product, ready to be launched
Use ESP32S3.
Define new PID to facilitate users to use this product
Company website link: https://lilygo.cc/
> Added LILYGO T-LoRa-Pager pids

- allocated-pids.txt
Allocate Glydr custom ID on ESP32 usb-pids
> Update allocated-pids.txt with Glydr pid

- allocated-pids.txt
A scientific instrument to observe zebrafish larvae. 
ESP32-S3
Custom driver & device identification through PID
[Noldus Information Technology BV - DanioVision](https://noldus.com/daniovision)
> Update allocated-pids.txt with DanioVision

- allocated-pids.txt
- Give a short description of the device and its function
- A portable USB-C microphone
- Tell us what chip you're using
- ESP32-S3
- Mention why you need a custom PID
- Additionally to UAC2 audio for recording we want to add a custom usb interface for configuring advanced options of the device through our own configuration GUI and want the device to be recognized by the product id
- If applicable/available mention your company and a link to the website of the product.
- https://soundskrit.ca
- https://www.kickstarter.com/projects/soundskrit/firefly-mic
> Add Soundskrit Firefly
