- allocated-pids.txt
I'm after 2x PIDs for my new TinyS2 development board using the new ESP32-S2FN4R2. One for Arduino/IDF and one for CircuitPython as the TinyS2 will be only using the native USB.
Btw, thanks HEAPS for making PIDs available - It's very generous and a huge help for small companies like mine that only do a few boards every year. 
Reason for custom PIDs are: 
**CircuitPython** - Adafruit require every board that runs CircuitPython to have a unique PID
**Arduino** - Having a unique PID allows the board to be listed against the port it's on in the ports dropdown list, so once flashed in the Arduino IDE for the first time, my TinyS2 would show up as TinyS2 instead of "generic ESP32 dev board" :)
I am requesting these PIDs on behalf on my Company, **Unexpected Maker** and though I don't have …
> Request PIDS for my new TinyS2 ESP32-S2 development board

- allocated-pids.txt
Desc: USB Crypto devices for development and security applications
Chip: ESP32-S2FH4
Why: For security reasons a dedicated PID adds extra checkpoints for the software in the host
Company: Wualabs LTD (https://wualabs.com)
> Requested PIDs for upcoming Wualabs - Wuard.io USB crypto devices

- allocated-pids.txt
Sorry, It seems I need a 3rd PID for my TinyS2 as the UF2 bootloader also requires a unique PID for the USB device when it boots as a mass storage device. TinyUF2 doesn't allow sharing of PIDs here.
> Added extra PID for UF2 Bootloader

- allocated-pids.txt
[This board](http://www.lilygo.cn/prod_view.aspx?id=1321) by LILYGO seems like a great option for someone to start tinkering with ESP32-S2.  
But, unfortunately the board manufacturer [does not have a USB VID](https://github.com/Xinyuan-LilyGO/LilyGo-T-Display-S2/issues/4).
I have [added support for CircuitPython for this board](https://github.com/adafruit/circuitpython/pull/3943), but to be able to get that merged, I need two unique and valid PIDs for this board. One for CircuitPython itself, and another for the UF2 bootloader (for when it boots up in mass-storage mode).
Also, Thanks a lot for offering these PIDs, they are an invaluable resource for open-source software.
Cheers
> Requesting PIDs for LILYGO TTGO T8 ESP32-S2

- allocated-pids.txt
I would love to use 3 PIDs for my new development board “ATMegaZero ESP32-S2” which uses the new ESP32-S2 chip.
**Reason for custom PIDs are:**
**CircuitPython -** Adafruit require every board that runs CircuitPython to have a unique PID
**Arduino -** In order to use a custom board on the Arduino IDE the board definition requires a unique PID to identify the board by its name. I would love to be able to display the board as “ATMegaZero ESP32-S2” and not with a generic USB name.
**UF2 Bootloader -** UF2 bootloader requires a unique PID for the USB device when it boots as a mass storage device.
I am requesting these PIDs on behalf of my own company EspinalLab, LLC. You can find the first version of the ATMegaZero at [www.atmegazero.com](https://atmegazero.com).  The new board is not posted …
> Added PIDs for the ATMegaZero ESP32-S2

- allocated-pids.txt
Can you allocate USB PIDS for the following board.
PIDs required:  Arduino, Circuitpython, UF2 Bootloader
Board: Gravitech Cucumber RIS
Processor: ESP32S2
Adafruit requires unique USB PIDs for all circuitpyython boards. 
https://www.gravitech.us/cursdebowise.html
Thanks,
> USB PIDS for Gravitech Cucumber RIS board

- allocated-pids.txt
Added variants of the Gravitech Cucumber boards
CucumberR   - WROVER module, no sensors
CucumberM  - WROOM module, no sensors
CucumberMS - WROOM module w/sensors
Processor: ESP32S2
PIDs needed for Arduino, Circuitpython and UF2 Bootloader
These are needed to differentiate between the boards when connected
> Gravitech R and M(S) variants added

- allocated-pids.txt
Hello, 
I would like to use 3 PIDs for Franzininho WIFI board which uses the ESP32-S2 Soc.
- CircuitPython - Adafruit require every board that runs CircuitPython to have a unique PID
- Arduino - In order to use a custom board on the Arduino IDE the board definition requires a unique PID to identify the board by its name. 
- UF2 Bootloader - UF2 bootloader requires a unique PID for the USB device when it boots as a mass storage device.
I am requesting these PIDs on behalf of Franzininho, an open source project. You can find the project on: https://github.com/Franzininho/Franzininho-WIFI
More Detais about Franzininho: https://franzininho.com.br/ https://www.instagram.com/franzininho
Thank you
> Adding USB PID for Franzininho WIFI

- allocated-pids.txt
I need some PIDs for adding CircuitPython and UF2 to our reference design (will create PRs once PIDs are assigned). The board will be used internally before shipping to make sure our sensors work as advertised, by our customers to get started with the sensor and for debugging.
The reference design is based on the ESP32-S2-WROVER module.
Company: Artisense GmbH
Website: https://artisense.ai
> Add Artisense Reference Design

- allocated-pids.txt
I would like to use 2 PIDs for the WROVER version of the [Muse Lab nanoESP32-S2](https://github.com/wuxx/nanoESP32-S2) board which feature an ESP32-S2 WROVER.
These IDs will be used for :
- [CircuitPython](https://circuitpython.org/) port
- UF2 [Bootloader](https://github.com/adafruit/tinyuf2)
I have no link with Muse Lab or Adafruit, I am just writing a port of CP for this board and need 2 unique PID as requested by Adafruit.
Many thanks to offer this possibility !
> Add nanoESP32-S2 WROVER board

- allocated-pids.txt
I'm requesting 2x PIDs for my new `FeatherS2 Neo` development board using the new ESP32-S2FN4R2. One for Arduino/IDF and one for CircuitPython.
CircuitPython - Adafruit require every board that runs CircuitPython to have a unique PID
Arduino - Having a unique PID allows the board to be listed against the port it's on in the ports dropdown list, so once flashed in the Arduino IDE for the first time, my FeatherS2 Neo would show up as UM FeatherS2 Neo instead of "generic ESP32 dev board" :)
I am requesting these PIDs on behalf on my Company, Unexpected Maker and though I don't have online info for my FeatherS2 Neo yet, here is what the boards looks like:
https://twitter.com/unexpectedmaker/status/1410055812584640525
Also, here are some links for my other ESP32 …
> Added Unexpected Maker FeatherS2 Neo - Arduino & CircuitPython

- allocated-pids.txt
USB PIDS for Morpheans MorphESP-240 developement board using ESP32S2
PIDS for UF2 Bootloader, Arduino, and CircuitPython
> Request USB-PIDS for MorphESP-240 ESP32-S2 board by Morpheans

- allocated-pids.txt
A brief description of what the device will do:  Testing Alcohol, store the mesurement values at a USB MSD
Which chip do you use: ESP32-S2
Why you need a custom PID: can't use the standard TinyUSB PIDs
Company name: CM Manufactory GmbH, Germany
> Eigene PID

- allocated-pids.txt
I'm requesting 9x PIDs for my 3 new ESP32-S3 development boards.
Arduino - Having a unique PID allows the board to be listed against the port it's on in the ports dropdown list, so once flashed in the Arduino IDE for the first time, my board will show up with their correct names, instead of "generic ESP32 dev board" :)
I am requesting these PIDs on behalf on my Company, Unexpected Maker - here's a look at my new boards:
https://youtu.be/rcTrYBtaAMc
Thanks!
> Added Unexpected Maker ESP32-S3 boards

- allocated-pids-espressif-devboards.txt
Espressif ESP32-S3 DevKitM-1
ESP32-S3
PIDs for TinyUF2 Bootloader and CircuitPython
> Add PIDs for Espressif ESP32-S3 DevKitM-1 board

- allocated-pids.txt
Hello, I would like to request 9 PIDs for our Banana Pi dev boards.
1. Banana Pi Leaf-S3 dev board with ESP32-S3 chip.
2. Banana Pi Leaf-S2 dev board with ESP32-S2 chip.
3. Banana Pi BPI:Bit v2 dev board with ESP32-S2 chip.
A PID of UF2 Bootloader, Arduino, and CircuitPython for each of these boards, 9 PIDs in total.
———————————————————
Custom PIDs are required due to:
UF2 / UF2-Bootloader - requires a unique PID for the USB device when it boots as a mass storage device as TinyUF2 doesn't allow sharing the same PIDs here.
Arduino - a unique PID allows the board to be listed by the proper board name instead of "generic ESP32 dev board"
CircuitPython - Adafruit requires every board that runs CircuitPython to have a unique PID.
———————————————————
I'm requesting these PIDs on behalf of my …
> Add PIDs for Banana Pi dev boards

- allocated-pids.txt
Hi, opening a request for PIDs for the Hiibot IOTS2.
- An ESP32-S2 based development board with smaller size (25.4*45.9mm), TFT-LCD, Battery Charging and Qwiic/STEMMA QT connector.
- ESP32-S2
- a custom PID required by tinyUF2
- a custom PID required by Circuitpython
- https://python4iots2.readthedocs.io/en/latest/index.html
- https://www.tindie.com/products/bradchan/hiibot-iots2/
Thanks
> Add PIDs for Hiibot IOTS2 dev board

- allocated-pids.txt
Development Board
ESPRESSIF-ESP32-S2-WROOM
LILYGO
http://www.lilygo.cn/prod_view.aspx?TypeId=50063&Id=1320&FId=t3:50063:3
This board is very similar to the one that is already present (`0x8006 | LILYGO TTGO T8 ESP32-S2 - Arduino` et al.) but there are some differences (not only the missing display).
Development Board
ESPRESSIF-ESP32-S2
LILYGO
http://www.lilygo.cn/prod_view.aspx?TypeId=50063&Id=1300&FId=t3:50063:3
I'm not affiliated with LILYGO but I keep them in the loop.
> LILYGO TTGO T8 ESP32-S2 ESP32-S2-WROOM and LILYGO TTGO T8 ESP32-S2 ESP32-S2 (no Display)

- allocated-pids.txt
Hi, im opening this PR for GoGo Board PIDs
- A short description of what the device is going to do (e.g. cat tracker with USB trace download)
> An educational devices
- What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
> ESP32-S3
- Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
> TinyUF2 and Arduino itself
- If you're requesting a PID on behalf of a company, please mention the name of the company
> LILCMU, LogixEd
- If applicable/available, a website or other URL with information about your product or company
> [GoGoBoard website](https://th.gogoboard.org)
> add PIDs for GoGo Board

- allocated-pids.txt
Hi, I would like to register these PIDs for our new Product
Industrial signaling device
ESP32-S2
The PIDs are required so that the PC Software can detect the product
WERMA Signaltechnik GmbH
[https://www.werma.com/de/landing/esign/](https://www.werma.com/de/landing/esign/)
> Add PIDs for eSIGN

- allocated-pids.txt
Hi,
I would like to register an additional PID for our Product.
Industrial signaling device
ESP32-S2
The PIDs are required so that the PC Software can detect and differentiate the product
Siemens
> Additional PID

- allocated-pids.txt
Hi, I would like to request to add the PID for Mixgo CE board
A development board for ESP32-S2 form Mixly Team
ESP32-S2
Mixly Team
[mixly.org](https://mixly.org/)
> Request PID for Mixgo CE board

- allocated-pids.txt
Hi there,
Here's a request for putting in my smart calendar project's USB product ID: 0x80FE
It's basically a low-power HMI device that talks to an API server. The API server takes an iCalendar feed (or something else later) and pushes it to the client device. The USB will be used for reading/writing configurations to the device (e.g. WiFi SSID, iCalendar feed URL etc.). It's not a standard CDC serial, and it will be much easier for the client app to detect the device when it is being connected.
Here's a reference for my project (server-side): https://github.com/huming2207/perpetcal-api
The firmware hasn't been started yet, but some research has been done, see here:
- https://twitter.com/huming2207/status/1503140566527197189
- https://twitter.com/huming2207/status/1520318409124110336
In …
> Add 0x80fe - PerpetCal Smart Calendar

- allocated-pids.txt
Hello. I would like to register these PIDs for my new board, MiniMain ESP32-S2.
> A short description of what the device is going to do:
A controller board for haunted attraction props. Control lighting, pneumatics, and sound.
> What chip are you using for the device the PID is allocated for
ESP32-S2
> If you're requesting a PID on behalf of a company, please mention the name of the company
At this moment it is just me. But may be a company named Department of Alchemy soon.
> If applicable/available, a website or other URL with information about your product or company
Here is the GitHub location for the board: https://github.com/DepartmentOfAlchemy/minimain-esp32-s2
> Allocate PIDs for MiniMain ESP32-S2

- allocated-pids.txt
Hi, I would like to request the relative PIDs for IoT-PostBox v1 board
> A short description of what the device is going to do (e.g. cat tracker with USB trace download)
It is a PostBox mail tracker that detects when you get a mail and notifies it using Wifi or Lora network.
> What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
It is based on an ESP32-S2 MCU
> Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
I need them to program it with CircuitPython, Arduino IDE and the Host application.
> If you're requesting a PID on behalf of a company, please mention the name of the company
No company at this time yet
> If applicable/available, a website or other URL with information about your product or company
The Kicad designs and …
> Allocate IoT-PostBox v1 board PIDs

- allocated-pids.txt
a debugger based on Espressif's esp-usb-bridge (https://github.com/espressif/esp-usb-bridge), which can debug ESP series chip.
ESP32-S2
for device identification，and someone may use it with arduino/circuitpython
MuseLab, we are a technical team from china
here is the github repo https://github.com/wuxx/ESPLink
> Allocate PIDs for MuseLab ESPLink

- allocated-pids-espressif-devboards.txt
The display is connected differently and there are buttons on the front.
> Add PIDs for ESP32S3 Box Lite

- allocated-pids.txt
Adding second variant of the Waveshare ESP32-S2-Pico with a LCD.
It needs own PIDs because the name is similar but the hardware is different.
> Add Waveshare ESP32-S2-Pico-LCD

- allocated-pids.txt
Add M5STACK S3 series boards.
Docs is not ready yet, once we're ready, you can see it [here](https://docs.m5stack.com/en/products?id=core) :)
> Add M5STACK S3 series boards

- allocated-pids.txt
Our products are in the process of migration to ESP32-S3.
We need custom PIDs because our PC side configurator software uses VID/PID pair to detect and identify the devices both will running and in bootloader mode.
> SUKU Intech Studio products added

- allocated-pids.txt
Hello, I would like to request 3 PIDs for Banana Pi BPI-PicoW-S3 dev boards, with ESP32-S3 chip.
A PID of UF2 Bootloader, Arduino, and CircuitPython.
———————————————————
Custom PIDs are required due to:
UF2 / UF2-Bootloader - requires a unique PID for the USB device when it boots as a mass storage device as TinyUF2 doesn't allow sharing the same PIDs here.
Arduino - a unique PID allows the board to be listed by the proper board name instead of "generic ESP32 dev board"
CircuitPython - Adafruit requires every board that runs CircuitPython to have a unique PID.
———————————————————
I'm requesting these PIDs on behalf of my company, Banana Pi.
Official website: https://banana-pi.org/
Many thanks for your time.
> Add PIDs for BPI-PicoW-S3

- allocated-pids.txt
Could you add PIDs for the CharaChorder Lite S2?
The device uses the ESP32-S2.
We need a custom driver for the UF2 bootloader and application.
The company is CharaChorder LLC
The product information is on our website here: https://www.charachorder.com/products/charachorder-lite
> Add PIDs for CharaChorder Lite-S2

- allocated-pids.txt
Hi,
Thanks for this service, its a great help!
1. A short description of what the device is going to do (e.g. cat tracker with USB trace download)
AXIS is a body tracking device, much like a motion capture suit.
2. What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
We are using the ESP32-S3.
3. Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
We need a custom PID as we are writing custom drivers/runtimes and we need to be able to detect that our device is 
connected.
4. If you're requesting a PID on behalf of a company, please mention the name of the company
I am requesting on behalf of Refract Technologies.
5. If applicable/available, a website or other URL with information about your product or company
Our company website is …
> Add PIDs for Refract AXIS

- allocated-pids.txt
&nbsp;&nbsp;&nbsp;&nbsp; Hello Jeroen,
1. SoftRF is a proximity awareness system for general aviation
2. We are using both ESP32-S2 and ESP32-S3
3. We need a custom PIDs to work with our custom [application software](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool)
4. [Website](https://github.com/lyusupov/SoftRF)
> Add PIDs for SoftRF devices

- allocated-pids.txt
Thank you in advance, love your work!
---------
Sensory Bridge is built from the ground up as an open, powerful bridge between sight and sound. With a show that's reactive to notation, vibrato and more, it produces very unique and pleasant-to-look-at light shows which synchronize to your music without any visible latency.
---------
I am using the ESP32-S2.
---------
I need a custom PID to allow for [VID:PID] device filtering in WebSerial applications!
---------
I am requesting on behalf of Lixie Labs.
---------
The product landing site for Sensory Bridge is:
https://sensorybridge.rocks/
The Software (MIT License) is:
https://github.com/connornishijima/SensoryBridge
The Hardware (CERN-OHL-W-2.0) is:
https://github.com/connornishijima/SensoryBridge/tree/main/extras/OSHW
Please let me know …
> Requesting PID 0x8131 for Sensory Bridge

- allocated-pids.txt
Dear Maintainers,
Please,  check this pull request.
1. Our Device have USB CDC and MSC function, Mainly used for file storage and communication.
2. We are using  ESP32-S3 On our already mass-produced products and several new products planned in the near future.
3. We need custom PIDs to work with our application software (https://coding.matatalab.com/), Mainly used for equipment identification and screening.
4. I request PIDs for my company(https://matatalab.com/)
> Add PIds for Matatalab devices

- allocated-pids.txt
Greetings Dear Colleagues,
I wish to apply for PIDs   0x813A, 0x813B, 0x813C and 0x813D.
1. Flash64 products are Flash IC Programmers for eMMC, UFS, NAND and SPI.
2. We are currently in the final stages of hardware development using an ESP32-S3-WROOM-1-N16R8 Module.
3. We need custom PIDs because we are using a Vendor Specific Interface Class for USB communication with our proprietary software.
4. Our company name is ShenZhen ZhengMa Electronic Ltd.
5. The website for the Flash64 product is still under development. It will be deployed sometime in 2Q2023. However, the url has already been reserved at www.flash64.com
Best Regards
> Add PIDs for Flash64

- allocated-pids.txt
Hello, I would like to request 12 PIDs for Deneyap Development Boards
- Deneyap Mini (ESP32-S2)
- Deneyap Mini v2 (ESP32-S2)
- Deneyap Kart 1A v2 (ESP32-S3)
- Deneyap Kart G (ESP32-C3)
I'm requesting these PIDs on behalf of my company, Deneyap Kart
Official website: https://deneyapkart.org/en/
> Add PIDs for Deneyap Development Boards

- allocated-pids.txt
PID codes for Chroma.tech Canopy controllers. 
Chroma.tech makes LED controllers for large scale art installations and architecture lighting. The controllers are based on ESP32-S3.
Custom PID will allow our online config software to easily filter for Chroma.tech devices with our company name in the Web Serial dialog.
https://chroma.tech
> Added PID codes for Chroma.tech Canopy

- allocated-pids.txt
Development Board with a screen and a rotary encoder with Leds
ESPRESSIF-ESP32-S3-WROOM
LILYGO
https://www.lilygo.cc/products/t-embed
https://github.com/Xinyuan-LilyGO/T-Embed
> Add Lilygo T-embed S3 board

- allocated-pids.txt
Development Board with a 128x128 screen and two buttons in a small form factor
ESPRESSIF ESP32-S3FN4R2
LILYGO
https://www.lilygo.cc/products/t-qt-pro https://github.com/Xinyuan-LilyGO/T-QT https://www.lilygo.cc/products/t-qt-v1-1 (now replaced with Pro but still around, only difference was lipo recharger on pro and varying flash/ram)
> Add LilyGo TTGO T-QT

- allocated-pids.txt
Development Board with one button, an RGB led, a grove port and some GPIOs
EspressIf ESP32-S3FN8
M5Stack
[https://docs.m5stack.com/en/core/AtomS3 20Lite](https://docs.m5stack.com/en/core/AtomS3%20Lite)
> Add M5Stack AtomS3 Lite board

- allocated-pids.txt
Development Board with one button, an RGB led, a I2C port, a microSD slot  based ESP32-S3-WROOM-1.
ESP32-S3-WROOM-1 (ESP32-S3)
WEMOS
[https://www.wemos.cc/en/latest/s3/s3_pro.html](https://www.wemos.cc/en/latest/s3/s3_pro.html)
> Add LOLIN S3 Pro board.

- allocated-pids.txt
I got this board off of ebay.
Some stuff of it is detailed here:
https://github.com/vcc-gnd/YD-ESP32-S3
I have no affiliation with the board maker.
I just got the board and want to make an official CircuitPython port.
I have already finished the technical side of the port.
> Add YD-ESP32-S3

- allocated-pids.txt
Development WiFi & Bluetooth 5 (LE) boards based ESP32-S3FH4R2.
ESP32-S3FH4R2
WEMOS
https://www.wemos.cc/en/latest/s3/s3_mini.html
> Add LOLIN S3 Mini board.

- allocated-pids.txt
Hi Spritetm！
I have revised the file, thank you!
ESP32-S3-0.42OLED Development boards based ESP32-S3FH4R2.
ESP32-S3FH4R2
TinyUF2 and ARduino, MicroPython,CircuitPython require unique PIDs for any new boards added
01Space
https://www.aliexpress.com/item/1005004942536689.html?spm=a2g0o.productlist.main.1.6d274562eGaNXP&algo_pvid=80819ad9-b2f2-40c9-b801-319 …
> Add 01Space ESP32-S3-0.42OLED boards 

- allocated-pids.txt
These devices make up the four parts of a sports scoring system. 
They are using ESP32-S3-WROOM-1 modules.
The devices will be a commercial product so require to have a professional driver installed, thus prefer to not use. TinyUSB as the PID. The Company is Talk All Sport, see talkallsport.com.
Thanks in advance
> Update to allocated PID for 4 devices for Talk All Sport

- allocated-pids.txt
I'm requesting 9x PIDs for my 3 new ESP32-S3 based boards.
The Boards
NanoS3 - A tiny ESP32-S3 based module that's compatible with my TinyPICO Nano board.
BlizzardS3 - A super small ESP32-S3 + ICE40 FPGA Hybrid board
Bling! - A tiny ESP32S3 board with 320x 1010 RGB Addressable LEDs on one side and everything including the kitchen sink.
Two boards feature the ESP32-S3FN8 + additional PSRAM and the Bling board uses an ESP32-S3-MINI1-8
Arduino - Having a unique PID allows the board to be listed against the port it's on in the ports dropdown list, so once flashed in the Arduino …
> Add new Unexpected Maker ESP32-S3 boards.

- allocated-pids.txt
Hello, I would like to request 3 PIDs for Banana Pi BPI-Centi-S3 dev boards, with ESP32-S3 chip.
A PID of UF2 Bootloader, Arduino, and CircuitPython.
———————————————————
Custom PIDs are required due to:
UF2 / UF2-Bootloader - requires a unique PID for the USB device when it boots as a mass storage device as TinyUF2 doesn't allow sharing the same PIDs here.
Arduino - a unique PID allows the board to be listed by the proper board name instead of "generic ESP32 dev board"
CircuitPython - Adafruit requires every board that runs CircuitPython to have a unique PID.
———————————————————
I'm requesting these PIDs on behalf of my company, Banana Pi.
[Official product  website](https://banana-pi.org/en/banana-pi-steam/147.html)
Many thanks for your time.
> Add Banana Pi BPI-Centi-S3 board.

- allocated-pids.txt
Could you add PIDs for the CharaChorder Engine S2, CharaChorder X S2, and CharaChorder X Host S2?
The Engine and the X are two different products. The Engine uses one ESP32-S2. The X uses two ESP32-S2 chips.
We need two PIDs for each device. One for the application and another for the UF2 bootloader.
The company is CharaChorder LLC
The product information is on our website here:
https://www.charachorder.com/products/charachorder-engine-pre-order
https://www.charachorder.com/products/charachorder-x
> Add PIDs for CharaChorder Engine S2 and CharaChorder X S2

- allocated-pids.txt
Hello Jeroen,
1. Development board with SA868 radio, PMU, GNSS, 128x64 OLED display and 21700 battery holder
2. ESPRESSIF ESP32-S3-WROOM-1-N16R8
4. LilyGO
5. https://www.lilygo.cc/products/t-twr-plus
> Add PIDs for LilyGO T-TWR Plus

- allocated-pids.txt
I'm requesting 12x PIDs for my 4 new ESP32-S3/C3 based boards.
The Boards
uPesy ESP32S3 Devkit - A devkit board based on a ESP32-S3 N16R8 module devkit board.
uPesy ESP32C3 Basic - A devkit board based on a ESP32-C3 module devkit board with ultra low power consomption in deep-sleep (<15µA).
uPesy ESP32C3 Pro - An improved version of  uPesy ESP32C3 Basic with built-in battery charging and a second LDO.
uPesy ESP32C3 Mini - A tiny devkit board based on the ESP32-C3-MINI module with ULP consomption in deep sleep.
Arduino - Having a unique PID allows the board to be listed …
> add uPesy C3/S3 boards

- allocated-pids.txt
Hello, 
I would like to request a PID for FLAM product made by the Lunii company.
It integrates a ESP32-S3 (USB) and an ESP32-MINI-1-N4 
———————————————————
Custom PIDs are required due to:
Usage as mass storage with PC software which has to be able to recognize the product based on PID.
———————————————————
I'm requesting these PIDs on behalf of my client, the Lunii company.
[Official product website](https://lunii.com/fr-fr/flam-baladeur-audio-interactif/)
Many thanks for your time.
> Add Lunii FLAM product (S3)

- allocated-pids.txt
&nbsp;&nbsp;&nbsp;&nbsp; Hello Jeroen,
1. SoftRF is a proximity awareness system for general aviation
2. We are using ESP32-S3 for the Midi Edition
3. We need a custom PIDs to work with our custom [application software](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool)
4. [Website](https://github.com/lyusupov/SoftRF)
> Add PIDs for ESP32-S3 SoftRF Midi device

- allocated-pids.txt
Adding PID for Waveshare ESP32-S3-pico board to be added to CircuitPython. 
https://www.waveshare.com/wiki/ESP32-S3-Pico
> Added Waveshare ESP32-S3-pico

- allocated-pids.txt
Guitar Reverb Pedal, using the ESP32-S2. I need the PID on behalf of VTR Effects as we are developing our software to control the pedal via USB communication.
https://vtreffects.com.br/produto/kailani-reverb-gold-series/
https://vtreffects.com.br/produto/narciso-delay/
https://vtreffects.com.br/produto/helios-overdrive-gold-series/
> Add PIDs for ESP32-S2 VTR Effects Guitar Pedal

- allocated-pids.txt
a keyboard based on Espressif's esp32-s3.It can also be used as an ESP32 development kit
ESP32-S3
for device identification，and someone may use it with arduino/circuitpython/micropython/tingyuf2
I'm a maker and love to do DIY work
here is the github repo  [https://github.com/MakerM0/MagiClick-esp32s3](https://github.com/MakerM0/MagiClick-esp32s3)
> Allocate PIDs for MagiClick S3

- allocated-pids.txt
I'm requesting 3x PIDs for my TinyWATCH-S3 project.
TinyWATCH-S3 will be an open-source ESP32-S3 based "everything + the kitchen sink" smartwatch project.
Arduino - Having a unique PID allows the board to be listed against the port it's on in the ports dropdown list, so once flashed in the Arduino IDE for the first time, my board will show up with their correct names, instead of "generic ESP32 dev board" :)
I am requesting these PIDs on behalf on my Company, Unexpected Maker
Thanks :)
> Add new Unexpected Maker TinyWATCH-S3 project.

- allocated-pids.txt
> A short description of what the device is going to do (e.g. cat tracker with USB trace download)
_T-Deck is a pocket-sized gadget with a 2.8-inch, 320 x 240 pixel IPS LCD display, a mini keyboard, and an ESP32 dual-core processor. While it's not exactly a smartphone, you can use your programming knowledge to turn it into a standalone messaging device, or coding software._
https://www.lilygo.cc/products/t-deck
> What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
ESP32-S3
> Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
Adding supported builds for MicroPython and CircuitPython.
> If you're requesting a PID on behalf of a company, please mention the name of the company
Requesting on behalf of LILYGO
> If applicable/available, …
> Allocate PIDs for LILYGO T-Deck

- allocated-pids.txt
I'm asking for 3 PIDs for our new senseBox MCU-S2 with ESP32-S2.
One each for Arduino, Circuit Python and the UF2 Bootloader
The senseBox MCU-S2 is an open source ESP32-S2 based board which will be mainly used in education and citizen science projects together with a series of sensors and other electronic components. A graphical (blockly) based programming interface (https://blockly.sesenbox.de) supports the young learners in developing their own project ideas. Sensor data gets published on the [openSenseMap](https://opensensemap.org/) and can used by everybody for free.
Arduino - Having a unique PID allows the board to be listed …
> Add senseBox MCU-S2 ESP32-S2

- allocated-pids.txt
> A short description of what the device is going to do (e.g. cat tracker with USB trace download)
ESP32-S3 PowerFeather is a development board focused on battery-powered/off-grid applications.
> What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
ESP32-S3
> Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
The PIDs will be used for Arduino (WIP) and CircuitPython (planned) support. For the former, it's so that the board can be properly associated with a friendly name in the IDE after firmware upload; for the latter, unique PID is required by Adafruit.
> If applicable/available, a website or other URL with information about your product or company
www.powerfeather.dev
> Add PIDs for ESP32-S3 PowerFeather

- allocated-pids.txt
Additional PID request to https://github.com/espressif/usb-pids/pull/123.
Hi @Spritetm, forgot the PID for UF2 bootloader. Other boards which has CircuitPython support applied for a PID for it, so I will also here (sorry, not too familiar yet with adding support for CircuitPython).
> Add UF2 bootloader PID for ESP32-S3 PowerFeather

- allocated-pids.txt
Pull request to add PIDs for the Columbia DSL Sensor board. This board is designed to be used as part of Columbia University's Digial Storytelling Lab's courses in physical computing. 
It uses an ESP32-S3-WROOM-1 and has various sensors for the students to easily interact with. 
We need unique PIDs to add the board to Arduino's board list and CircuitPython (Adafruit requires unique PIDs for CircuitPython and UF2 bootloader).
The board is being designed by my company, Double Take Labs.
www.doubletake.design
> Updated allocated-pids.txt

- allocated-pids.txt
I would like to register an PID for my product.
Reads connected keyboard input and retransmits it to a wireless protocol, to make a wired keyboard wireless
ESP32-S3
I want to create a firmware updater program (and possibly remapper) and I want it to automatically detect my device
My own startup
https://sterling-key.com/
> SterlingKey

- allocated-pids.txt
Hello, I would like to register a PID on behalf of my company (@KesongTech).
1. A short description of what the device is going to do (e.g. cat tracker with USB trace download)
This device acts as the receiver for our full-body motion capture system. 
2. What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
ESP32-S2
3. Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
Our driver and update tool relies on PID to recognize the receiver. And we are going to open source this product for public usage.
4. If you're requesting a PID on behalf of a company, please mention the name of the company
KesongTech (@KesongTech)
5. If applicable/available, a website or other URL with information about your product or company
Sorry that we do not …
> Add Meocap device

- allocated-pids.txt
Hello. I would like to assign a PID to the firmware for the ESP32-S3 that I have created and am planning to sell.
・A short description of what the device is going to do (e.g. cat tracker with USB trace download)
Macro device with customizable screen from browser
・What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
ESP32-S3
・Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
We would like to automatically detect the device, and when commercializing it, we would like to have it assigned a PID.
・If you're requesting a PID on behalf of a company, please mention the name of the company
I'm still an individual. There is a possibility that I will start my own corporation in the future, but it is undecided.
・If applicable/available, a …
> Add Chameleon Key

- allocated-pids.txt
A development board with keyboard, display and battery
ESP32-S3FN8
TinyUF2 and CircuitPython require unique PIDs for any new boards added. I'm also adding an Arduino PID.
M5Stack
https://docs.m5stack.com/en/core/Cardputer
> Add M5Stack Cardputer PIDs

- allocated-pids.txt
A development board with a round display and a rotary knob
ESP32-S3FN8
TinyUF2 and CircuitPython require unique PIDs for any new boards added. I'm also adding an Arduino PID.
M5Stack
https://docs.m5stack.com/en/core/M5Dial
> Add PID for M5Stack Dial

- allocated-pids.txt
1 Watt LoRa GPS Tracker for HAM operators
ESP32-S3 Mini
Custom design & build
QRP Labs
https://github.com/lightaprs/LightTracker-Plus-1.0
https://shop.qrp-labs.com/aprs
> 0x81E0 | QRP Labs - LightTracker Plus

- allocated-pids.txt
Guitar Delay Pedal, using the ESP32-S2. I need the PID on behalf of VTR Effects as we are developing our software to control the pedal via USB communication.
https://vtreffects.com.br/produto/narciso-delay/
>  Add PIDs for ESP32-S2 VTR Effects Guitar Pedal - Narciso Black

- allocated-pids.txt
> A short description of what the device is going to do (e.g. cat tracker with USB trace download)
T-Keyboard-S3 is an intelligent key controller developed based on the ESP32-S3-WROOM-1 module. It is different from traditional controllers as it features a 0.85-inch 128x128 RGB pixel LCD screen above the keys. It is connected to the main control board of the baseboard through an FPC ribbon cable.
https://www.lilygo.cc/products/t-keyboard-s3
> What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
ESP32-S3
> Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
Adding supported builds for MicroPython and CircuitPython.
> If you're requesting a PID on behalf of a company, please mention the name of the company
Requesting on behalf of …
> Allocate PIDs for LILYGO T-Keyboard S3

- allocated-pids.txt
This is a [new board from Waveshare](https://www.waveshare.com/wiki/ESP32-S3-Tiny), and I need a unique VID/PID in order to add CircuitPython support for the board. I'm not affiliated with Waveshare in any way, just a hobbyist.
ESP32-S3
It is required by the CircuitPython project
N/A
N/A
> Add new entry for ESP32-S3-Tiny

- allocated-pids.txt
I would like to request two PIDs on behalf of my Company `Wirmo` for a product called `SkysyLight`. One PID will be for the product and the other for the UF2 Bootloader.
Chip: ESP32-S2
Busylight: This will allow the PC software to uniquely identify the product to communicate with it.
UF2: This will allow for software updates
Company Website: https://wirmo.de
> Add SkysyLight to allocated-pids.txt

- allocated-pids.txt
I'm requesting 6x PIDs for 2 new boards from Unexpected Maker.
My first board is my new FeatherS3 Neo which is  an ESP32-S3 based Feather format board that has a 7x7 RGB LED matrix on it.
The second board is something new and very cool that I can't really go into publicly `yet`, but it's ESP32-S3 based, with a lot of RGB and other cool stuff, but here's a tease...
https://x.com/unexpectedmaker/status/1779077577946411154
Arduino - Having a unique PID allows the board to be listed against the port it's on in the ports dropdown list, so once flashed in the Arduino IDE for the …
> Added 2 new UM boards

- allocated-pids.txt
- We are developing a product which has shows up as having 2 USB ports, one for an application and one for logging. On our customer facing configuration website [link](https://umd.com.au/m320/), we need an additional PID to filter on, such that customers' do not see the additional port when selecting a device.
- ESP32-S3
- We need a custom PID as we are writing a custom 
- Applying on the behalf of Unique Micro Design (UMD)
- Website [link](https://umd.com.au/)
> Add UMD to allocated-pids.txt

- allocated-pids.txt
USBHID Joystick with Force Feedback interface
ESP32-S2
It is required for PC App software communication
N/A
N/A
> Add EMCFFB

- allocated-pids.txt
- Device description: USB stick for automation and pentesting
- Chip: ESP32-S3-Mini-1
- Reason for PID: required by CircuitPython
- Company: ThingPulse
- URL with more information: https://thingpulse.com/product/esp32-s3-pendrive-s3-128mb/
Kind regards,
Daniel
> Add ThingPulse Pendrive S3

- check-file-format.sh
CI ignores the last line added if it does not end in a newline, which allows errors to fall through. This fixes that.
> CI script: Also check last line of file if there is no newline

- allocated-pids.txt
- Device description: main modules (One Touch and One XLR) of modue® modular console 
- Chip: ESP32-S3
- Reason for PID: custom USB composite device and custom device driver
- Company: modue®
- URL with more information: https://www.modue.com/
Kind regards,
Piotr Daniel
> allocate modue® devices PIDs

- allocated-pids.txt
Hello Jeroen,
1. Development board with LoRa radio, 128x64 OLED display and micro-SD card adapter
2. ESPRESSIF ESP32-S3FH4R2
4. LilyGO
5. https://www.lilygo.cc/products/t3s3-v1-0
> Add PIDs for LilyGO T3-S3

- allocated-pids.txt
More info on the board can be found here:
[https://github.com/Xinyuan-LilyGO/T-Display-S3-Pro](https://github.com/Xinyuan-LilyGO/T-Display-S3-Pro)
[https://www.lilygo.cc/products/t-display-s3-pro](https://www.lilygo.cc/products/t-display-s3-pro)
> Added PID for LILYGO T-Display-S3-Pro board

- allocated-pids.txt
This  PR is for the Lilygo T4-S3 board
1. Espressif ESP32-S3R8
2. Adafruit requires unique PIDs for Circuitpython, TinyUF2 and Arduino
3. https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series
https://www.lilygo.cc/en-ca/products/t4-s3
> Add PIDS for Lilygo T4-S3

- allocated-pids.txt
This PR is for the LOLIN S3 Mini Pro
1. Espressif ESP32-S3FH4R2
2. Requires unique PIDs for Circuitpython, TinyUF2 and Arduino
3. https://www.wemos.cc/en/latest/s3/s3_mini_pro.html
> Add PIDS for LOLIN S3 Mini Pro

- allocated-pids.txt
Hi, I would like to register a PID for our new Product
Industial Signal Device 
ESP32-S2
The PIDs are required so that the PC Software can detect the product
WERMA Signaltechnik GmbH + Co. KG
https://www.werma.com/de/
> Added new PID for MC55 Touch Smart by WERMA Signaltechnik GmbH + Co.KG

- allocated-pids.txt
Adding PID for Waveshare ESP32-S3-Touch-LCD-1.69 & ESP32-S3-LCD-1.69 boards to be added to CircuitPython and arduino-esp32.
For [ESP32-S3-Touch-LCD-1.69](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.69)
For [ESP32-S3-LCD-1.69](https://www.waveshare.com/wiki/ESP32-S3-LCD-1.69)
arduino pr: [espressif/arduino-esp32/pull/10118](https://github.com/espressif/arduino-esp32/pull/10118)
> Added PIDs for Waveshare ESP32-S3-Touch-LCD-1.69 and ESP32-S3-LCD-1.69

- allocated-pids.txt
I'm requesting 3x PIDs for my new OMGS3 Board
One each for CircuitPython/MicroPython, Arduino and the UF2 Bootloader
OMGS3 is the smallest ESP32-S3 based fully featured board/module in the world - at just 25x10mm in size.
https://unexpectedmaker.com/omgs3
Arduino - Having a unique PID allows the board to be listed against the port it's on in the ports dropdown list, so once flashed in the Arduino IDE for the first time, my board will show up with their correct names, instead of "generic ESP32 dev board" :)
I am requesting these PIDs on behalf of my Company, Unexpected Maker
Thanks :)
> Added Unexpected Maker OMGS3

- allocated-pids.txt
ATLNS Flasher
ESP32-S3
Need a unique PID to identify the device.
ATLNS Semiconductor Technology (Xiamen) Co., LTD
https://www.atlns.cn/
> Add pid for ATLNS Flasher

- allocated-pids.txt
Adding PID for Waveshare ESP32-S3-Zero board to be added to CircuitPython, arduino-esp32 and PlatformIO.
Product wiki: [ESP32-S3-Zero](https://www.waveshare.com/wiki/ESP32-S3-Zero)
> Add PIDs for Waveshare ESP32-S3-Zero

- allocated-pids.txt
Added ESP32-S3-Touch-LCD-4.3, ESP32-S3-Touch-LCD-4.3B, ESP32-S3-Touch-LCD-7, ESP32-S3-Touch-LCD-5, ESP32-S3-Touch-LCD -5B and ESP32-S3-Touch-LCD -4 PID
wiki:
1.[ESP32-S3-Touch-LCD-4.3](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3)
2.[ESP32-S3-Touch-LCD-4.3B](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3B)
3.[ESP32-S3-Touch-LCD-7](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-7)
4.[ESP32-S3-Touch-LCD-5](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-5)
5.[ESP32-S3-Touch-LCD-5B](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-5)
6.[ESP32-S3-Touch-LCD-4](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4)
> Waveshare Added PIDs

- allocated-pids.txt
The device has not been officially released, and is mainly used for Internet of Things, automation and scalability products.PID is used for ESP32-S3,Company products, convenient to increase visibility,Company name: Waveshare.official website URL:https://www.waveshare.net/
> add Waveshare ESP32-S3-Touch-AMOLED-2.41

- allocated-pids.txt
Adding Barduino PID's.
Barduino is a development board created by Fablab Barcelona as a tool for it's educational programs. 
ESP32-S3 (ESP32-S3-WROOM-1)
It needs a custom PID to have the opportunity to show it officialy in the CircuitPython website and to create an Arduino core for it. 
It's done under Fablab Barcelona, part of IAAC. 
This is (will be because it's a WIP) the documentation for the board https://fablabbcn-projects.gitlab.io/electronics/barduino-docs/
and this is Fablab Barcelona https://fablabbcn.org/
and this IAAC https://iaac.net/
Thank you!
> Add Barduino PID's

- allocated-pids.txt
Re-Request with appropriate Template and updated "Manufacturer".
For traceability, this references #181, which was closed because of a pull request template issue and needed a change to the "manufacturer".
This is about the "ESP32-S3 Super Mini" dev boards found on Aliexpress and other chinese marketplaces.
Since no original manufacturer or creator could be found, I'm adding these as "Generic" brand, to be able to reference them in other projects for Arduino Core, Circuit-/MicroPython and TinyUF2.
They use the "ESP32-S3FH4R2" Variant without any additional USB-UART bridge and only rely on the internal 4MB Flash and 2MB PSRAM.
Some basic info can be found on [this chinese site](https://www.nologo.tech/product/esp32/esp32s3supermini/esp32S3SuperMini.html).
> Add PIDs for  ESP32 S3 Super Mini

- allocated-pids-espressif-devboards.txt
more detail for [ESP32-S3-LCD-EV-Board v1.5](https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-lcd-ev-board/user_guide.html)
> Add PIDs for ESP32-S3-LCD-EV-Board v1.5

- allocated-pids.txt
I have made some adjustments. These models are the ones our company will be working on next. Upon project completion, they will be named accordingly and uploaded to the wiki. You can check our official website at: https://www.waveshare.net/
> add Waveshare ESP32-S3-Touch-AMOLED-1.91, Waveshare ESP32-S3-Touch-AMOLED-1.64, and Waveshare ESP32-S3-Touch-AMOLED-1.43

- allocated-pids.txt
add new board: CircuitArt ESP32S3 CamTFT
This device has not been officially released and is mainly used for educational purposes. 
It uses the ESP32S3 chip. 
Custom PIDs are required to have it officially recognized on the CircuitPython website and to create an Arduino core for it, as well as a tinyUF2 bootloader.
more details: https://github.com/CircuitART/ESP32S3CamTFT/tree/main
Thanks
> add new board: CircuitArt ESP32S3 CamTFT

- allocated-pids.txt
CharaChorder Two S3 is a chording enabled USB keyboard.
ESP32-S3
The device pairs with serial applications that need PIDs for filtering valid devices
CharaChorder, LLC
The produce page is not live yet, but will be here:
https://www.charachorder.com/products/charachorder-two
> added CharaChorder Two S3

- allocated-pids.txt
Add PIDs for Waveshare ESP32-S3-Touch-AMOLED-1.8 board to be added to CircuitPython, arduino-esp32 and PlatformIO.
Product wiki: The wiki is not yet ready for release
btw, I'm a waveshare employee
> Add PIDs for Waveshare ESP32-S3-Touch-AMOLED-1.8

- allocated-pids.txt
- Give a short description of the device and its function, 
+ Device for transfer heart rate data from BLE HR sensor through USB
- Tell us what chip you're using, 
+ ESP32-S3
- Mention why you need a custom PID
+ For the use custom driver and a better user experience.
- If applicable/available mention your company and a link to the website of the product.
+ Piston Ltd. - Budapest - medical device manufacturer - https://www.pistonmedical.com/
> Add pid 0x8293 | Piston Medical - BLE Heart Rate Monitor Adapter

- allocated-pids.txt
Graphite-S3 - board with lipo charger, APA102-2020 led and uninified I2C connector. This board is the next generation of the Graphite family of boards, featuring an ESP32-S3 SoC (previous version - Graphite-S2). Used for learning of IOT, Robotics and python programming (circuitpython). Inspired by the Sparkfun dev boards.
What chip are you using for the device the PID is allocated for (e.g. ESP32-S3)
ESP32-S3-WROOM-1-N8
use for arduino/circuitpython, device identification
RobotClass - We teach electronics and make our own hardware, hardware shop
If applicable/available, a website or other URL with information about your …
> Add PIDs for RobotClass Graphite S3 board

- allocated-pids.txt
Hello
I'm developing open source model railway hardware under the name OpenRemise. This development has been going on for 3 years now and has gone through several prototypes with different processors and drive circuits. Among other things, it has also contributed to me adding stub support for the [esp-serial-flasher](https://github.com/espressif/esp-serial-flasher) :smile:.
Anyhow, I'm about to launch the first fully integrated version of my command station in a couple of months, the `S3Main`.
I've already registered the domain [openremise.at](https://openremise.at/) but there is not a lot of information on it yet. The device could use its own PID to register with a PC software that loads software updates and sound projects into locomotive decoders.
Best regards
Vincent
> Add PID for OpenRemise - S3Main

- allocated-pids.txt
- Give a short description of the device and its function
USB and WiFi source-measure unit for semiconductor characterisation
- Tell us what chip you're using,
ESP32-S3
- Mention why you need a custom PID
Custom driver & device identification through PID
- If applicable/available mention your company and a link to the website of the product.
Undalogic Ltd. (United Kingdom) - Test & Measurement equipment manufacturer - https://www.undalogic.com/
> Add PID for Undalogic miniSMU MS01

- allocated-pids.txt
Hi! Added the VID/PID for the MIDI controller we're building: MIDI Dobrynya.
It is a USB/BLE MIDI controller with advanced configuration capabilities.
The chip used are variations of ESP32-S3 modules
We need a custom PID for factory-related configuration which may rely on a custom driver, as well as for identification for our configuration software (hence the difference between bootloader / non-bootloader PIDs).
The website is https://mididobrynya.com/
Thank you for your consideration:)
> Add MIDI Dobrynya

- allocated-pids.txt
**Neway Navpad Controller [mini]**
Product in development, company website: https://www.newaydata.com
A USB-C peripheral to provide power, a joystick and physical buttons to a navigation tablet. We use an ESP32-S3 with TinyUSB but need to implement features beyond standard HID classes.
To enable us to create and certify a custom driver, we need custom PIDs. There are two variants, each with a bootloader.
> Add neway navpad

- allocated-pids.txt
1. Flexbar is a versatile touch bar powered by the ESP32-S3, designed to provide functionality similar to the Apple Touch Bar. It has successfully raised $330K on Kickstarter.
2. ESP32-S3
3. We need a custom PID for the accompanying software (FlexbarDesigner) to automatically recognize and connect to Flexbar.
4. ENIAC (HK) Technology Ltd.  深圳市本栖电子科技有限公司
5. https://eniacelec.com/   
https://www.kickstarter.com/projects/1735591421/flexbar-a-versatile-and-fully-customizable-touch-bar-solution
> Add PID for Enilinx Flexbar

- allocated-pids.txt
1. Flexbar-CDC is a versatile touch bar powered by the ESP32-S3, designed to provide functionality similar to the Apple Touch Bar.
2. ESP32-S3
3. **We need a new PID to distinguish between devices using the USB-HID protocol and those using the USB-CDC protocol.**
4. ENIAC (HK) Technology Ltd.  深圳市本栖电子科技有限公司
5. https://eniacelec.com/   
https://www.kickstarter.com/projects/1735591421/flexbar-a-versatile-and-fully-customizable-touch-bar-solution
> Add PID for Enilinx Flexbar-CDC

- allocated-pids.txt
[LILYGO T-Dongle S3](https://lilygo.cc/products/t-dongle-s3)
It's a USB dongle containing an ESP32-S3, 0.96" LCD Display, and SD card slot.
PID is needed to add CircuitPython support.
I am not affiliated in anyway with LILYGO.
> Allocate PIDs for LILYGO T-Dongle S3

- allocated-pids.txt
An unbranded, red development/breakout board sold on AliExpress (such as [L1](https://vi.aliexpress.com/item/1005006307343006.html), [L2](https://vi.aliexpress.com/item/1005008212569068.html), [L3](https://vi.aliexpress.com/item/1005007477549296.html)) that has a USB Type-C port.
ESP32-S2-WROOM
For [this pull request](https://github.com/adafruit/circuitpython/pull/10060) to add this board to CircuitPython.
> Generic Red ESP32-S2-WROOM with Type-C

- allocated-pids.txt
Heltec Vision Master e290 LoRa Epaper device.
ESP32-S3.
Requesting as a developer unassociated with Adafruit and Heltec for use developing CircuitPython support for this dev board.
> Added Heltec Vision Master 290

- allocated-pids.txt
Hello,
I would like to allocate a new PID for our product.
- A short description of what the device is going to do (e.g. cat tracker with USB trace download)
Industial Signal Device
- What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
ESP32-S2
- Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)
The PID is used for our PC-Software to detect the product 
- If you're requesting a PID on behalf of a company, please mention the name of the company
WERMA Signaltechnik GmbH + Co.  KG
- If applicable/available, a website or other URL with information about your product or company
https://www.werma.com/
Thank you!
> Allocate PID for LineLIGHT Fusion Smart by WERMA Signaltechnik GmbH + Co. KG 

- allocated-pids.txt
The board is Waveshare part No ESP32-S3-Touch-LCD-2
_ESP32-S3 2inch Capacitive Touch Display Development Board_
https://www.waveshare.com/esp32-s3-touch-lcd-2.htm?sku=29667
I am not affiliated with Waveshare.
I noticed there are a few Waveshare LCD boards that were added, but this one was not in there.
PRs for Circuitpython and tinyUF2 are ready to go.
> add Waveshare ESP32S2 Touch LCD 2 for tinyuf2 and Circuitpython

- allocated-pids.txt
Hello,
I'm looking to get a custom PID for an open-source project our makerspace is developing. It is an Access Control System, allowing us to limit access to equipment based on trainings, and monitor who is using the equipment. 
The system is built around an ESP32-S2, we're specifically using the ESP32-S2-MINI-2-N4 module on our board. 
The custom PID will be used so that a configuration program we are writing (for setting system settings via USB) can detect the device and automatically connect to it. 
This is being developed by the Rochester Institute of Technology SHED Makerspace. More info at; https://github.com/rit-construct-makerspace/access-control-hardware/wiki (mostly pertaining to the last revision of the hardware, but same operating concept). 
If this PID is taken by another …
> Add SHED Access Control Core

- allocated-pids.txt
Hello Jeroen,
1. ThinkNode M2 LoRa Signal Transceiver with 1.3” OLED Display
2. ESPRESSIF ESP32-S3
4. https://www.elecrow.com/thinknode-m2-meshtastic-lora-signal-transceiver-powered-by-esp32-s3-with-1-3-oled-display.html
> Add Elecrow ThinkNode M2

- allocated-pids.txt
I'm requesting 3x PIDs for my new EDGES3 Board and 3x PIDs for my new product - SQUiXL.
One each for CircuitPython/MicroPython, Arduino and the UF2 Bootloader
EDGES3 is my new ESP32-S3 based, fully featured module that uses an m.2 connector for reusability on carrier boards.
My product page is it not public yet, but here's a picture of an unpopulated board, because I'm at home and don't have pics of a populated prototype here.
SQUiXL is an ESP32-S3 based portable touch screen device that packs in a huge amount of peripherals, including I2S amp + speaker, haptics, low power RTC, battery + FG, uSD card slot, magnetic charge/USB and of course the beautiful 480x480 tricolor screen :)
Again, the product page is not public yet, but here's a photo of SQUiXL with a bunch of case colors.
Reason …
> Added Unexpected Maker EDGES3 and SQUiXL

- allocated-pids.txt
Added:
0x82E3 | Domino4 - CWS - Springbot (ESP32-S2) - UF2 Bootloader
> 0x82E3 | Domino4 - CWS - Springbot (ESP32-S2) - UF2 Bootloader

- allocated-pids.txt
Hello Jeroen,
1. Wireless-tag WT99P4C5 board
2. ESPRESSIF ESP32-P4
4. https://github.com/wireless-tag-com/DevBoard/tree/WT99P4C5-S1
PIDs are requested to follow previous PR #243 
Unfortunately this [**breaks logic of CI Actions build**](https://github.com/espressif/usb-pids/actions/runs/15940988965)
> Add Wireless-tag WT99P4C5

- allocated-pids.txt
Add Deneyap Kart v2 PID
Deneyap Kart v2 is an updated version of Deneyap Kart. It is powered by ESP32-S3. 
[Visit our store](https://magaza.deneyapkart.org/tr/product/gelistirme-kartlari/) for all development kits.
You can access the documentation [on our github page](https://github.com/deneyapkart).
> Add Deneyap Kart v2 PID

- allocated-pids.txt
HI Spritetm,
I have completely rework the changes into a new commit.  Let's try this new pull request again.
Thank you!  
Add Waveshare ESP32-S3-Touch-AMOLED-1.75:
Product link: https://www.waveshare.com/product/esp32-s3-touch-amoled-1.75.htm?sku=31262
Allocate PIDs for Arduino, CircuitPython/MicroPython, and UF2 Bootloader.
0x828D | Waveshare ESP32-S3-Touch-AMOLED-1.75 - Arduino
0x828E | Waveshare ESP32-S3-Touch-AMOLED-1.75 - CircuitPython/MicroPython
0x828F | Waveshare ESP32-S3-Touch-AMOLED-1.75 - UF2 Bootloader
> Add Waveshare ESP32-S3-Touch-AMOLED-1.75

- allocated-pids.txt
**Description:** We are primarily a software company. However, on occasion clients do require boutique hardware solutions. When working with these we quite often interact with industry/proprietary hardware and cannot guarantee the hardware that will be used along side it. Since we currently use `ESP32-S3` in situations like these having a dedicated `PID` ensures reliable enumeration and prevents driver or PID conflicts across deployments.
**Chip:** `ESP32-S3`
**Why:** Because when delivering to a client we can't risk a already populated `PID` interfering with our software solutions.
**Company:** [Sentient Computing (https://sencom.com.au/)](https://sencom.com.au/)
> Added a PID for Sentient Computing

- allocated-pids.txt
CharaChorder Forge Trackball S2 is a USB trackball that can also integrate with chording enabled Forge keyboards.
ESP32-S2FH4
The device pairs with serial applications that need PIDs for filtering valid devices
CharaChorder, LLC
The product is currently bundled with this product:
https://forgekeyboard.com/products/master-forge-premium
> add PIDs for CharaChorder Forge Trackball

- allocated-pids.txt
Hi, @Spritetm 
It's new ESP32-S3 Dev Board FoBE Quill ESP32-S3 Mesh
Chip: ESP32-S3
Product link: [https://docs.fobestudio.com/product/f1102](https://docs.fobestudio.com/product/f1102)
Vendor: FoBE Studio
0x82F4 | FoBE Quill ESP32-S3 Mesh - Arduino
0x82F5 | FoBE Quill ESP32-S3 Mesh - CircuitPython/MicroPython
0x82F6 | FoBE Quill ESP32-S3 Mesh - UF2 Bootloader
Thank you!
> Add PIDs for FoBE Quill ESP32-S3 Mesh

- allocated-pids.txt
Hello Jeroen,
1. ThinkNode M5 LoRa Signal Transceiver with 1.54" e-Paper display
2. ESPRESSIF ESP32-S3
4. https://www.elecrow.com/thinknode-m5-meshtastic-lora-signal-transceiver-esp32-s3-1-54-screen-gps-function.html
> Add Elecrow ThinkNode M5

- allocated-pids.txt
Includes PIDs from pending pull request for commit "rsoric:main".
Vulintus creates custom research equipment used in clinical biomedical research. The ESP32-S3 used in our RePlay IMU device coordinates multiple position and movement sensors to measure hand and arm movements during physical rehabilitation. We need a custom PID so that the device is automatically discoverable on systems that might have other ESP32-based devices connected.
www.vulintus.com
> Added PID for Vulintus RePlay IMU.
